import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  todoRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  checkbox: {
    width: 25,
    height: 25,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#98a69d",
    borderRadius: 8,
  },
  checkboxDone: { borderColor: "#176b47", backgroundColor: "#176b47" },
  check: { fontWeight: "900", color: "#fff" },
  flex: { flex: 1 },
  todoTitle: { fontSize: 15, fontWeight: "600", color: "#26372d" },
  done: { color: "#9aa49e", textDecorationLine: "line-through" },
  metaRow: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 6, marginTop: 5 },
  chip: {
    overflow: "hidden",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 99,
    backgroundColor: "#eaf4ed",
    fontSize: 11,
    color: "#256543",
  },
  meta: { fontSize: 11, color: "#7b867f" },
  overdue: { fontWeight: "700", color: "#b24038" },
  action: { fontSize: 12, color: "#65736b" },
  danger: { color: "#a43d35" },
  editor: { gap: 8, paddingTop: 8 },
  input: {
    minHeight: 46,
    paddingHorizontal: 13,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#d9e1da",
    borderRadius: 12,
    backgroundColor: "#fbfcfb",
    color: "#17251e",
  },
  multiline: { minHeight: 76, textAlignVertical: "top" },
  row: { flexDirection: "row", alignItems: "center", gap: 8 },
  secondaryButton: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 15,
    borderWidth: 1,
    borderColor: "#bad0c1",
    borderRadius: 12,
    backgroundColor: "#eef6f1",
  },
  secondaryText: { fontWeight: "700", color: "#176b47" },
  primaryText: { fontWeight: "700", color: "#fff" },
  subList: {
    gap: 9,
    marginTop: 3,
    paddingTop: 11,
    paddingLeft: 35,
    borderTopWidth: 1,
    borderTopColor: "#edf0ed",
  },
  subRow: { flexDirection: "row", alignItems: "center", gap: 9 },
  smallCheck: {
    width: 21,
    height: 21,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#98a69d",
    borderRadius: 7,
  },
  miniButton: {
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "#176b47",
  },
});
