import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  page: {
    width: "100%",
    maxWidth: 1180,
    alignSelf: "center",
    gap: 14,
    paddingHorizontal: 28,
    paddingTop: 22,
    paddingBottom: 100,
  },
  heading: { fontSize: 30, fontWeight: "800", color: "#17251e" },
  muted: { marginTop: 3, color: "#748078" },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  cardTitle: { fontSize: 17, fontWeight: "700", color: "#213128" },
  row: { flexDirection: "row", alignItems: "center", gap: 8 },
  flex: { flex: 1 },
  input: {
    minHeight: 46,
    paddingHorizontal: 13,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#d9e1da",
    borderRadius: 12,
    backgroundColor: "#fbfcfb",
    color: "#17251e",
  },
  multiline: { minHeight: 76, textAlignVertical: "top" },
  primaryButton: {
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    borderRadius: 12,
    backgroundColor: "#176b47",
  },
  primaryText: { fontWeight: "700", color: "#fff" },
  secondaryButton: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 15,
    borderWidth: 1,
    borderColor: "#bad0c1",
    borderRadius: 12,
    backgroundColor: "#eef6f1",
  },
  secondaryText: { fontWeight: "700", color: "#176b47" },
  ghostButton: { padding: 9 },
  ghostText: { fontWeight: "700", color: "#176b47" },
  segment: {
    flexDirection: "row",
    gap: 4,
    padding: 4,
    borderRadius: 14,
    backgroundColor: "#e7ece8",
  },
  segmentItem: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 10,
    borderRadius: 10,
  },
  segmentActive: { backgroundColor: "#fff" },
  segmentText: { fontWeight: "600", color: "#738078" },
  segmentTextActive: { color: "#176b47" },
  disabled: { opacity: 0.4 },
  empty: { paddingVertical: 45, textAlign: "center", color: "#8a958e" },
  todoRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  checkbox: {
    width: 25,
    height: 25,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#98a69d",
    borderRadius: 8,
  },
  smallCheck: {
    width: 21,
    height: 21,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#98a69d",
    borderRadius: 7,
  },
  checkboxDone: { borderColor: "#176b47", backgroundColor: "#176b47" },
  check: { fontWeight: "900", color: "#fff" },
  todoTitle: { fontSize: 15, fontWeight: "600", color: "#26372d" },
  done: { color: "#9aa49e", textDecorationLine: "line-through" },
  action: { fontSize: 12, color: "#65736b" },
  danger: { color: "#a43d35" },
  metaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 6,
    marginTop: 5,
  },
  meta: { fontSize: 11, color: "#7b867f" },
  overdue: { fontWeight: "700", color: "#b24038" },
  chip: {
    overflow: "hidden",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 99,
    backgroundColor: "#eaf4ed",
    fontSize: 11,
    color: "#256543",
  },
  editor: { gap: 8, paddingTop: 8 },
  subList: {
    gap: 9,
    marginTop: 3,
    paddingTop: 11,
    paddingLeft: 35,
    borderTopWidth: 1,
    borderTopColor: "#edf0ed",
  },
  subRow: { flexDirection: "row", alignItems: "center", gap: 9 },
  miniButton: {
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "#176b47",
  },
  weekdays: { flexDirection: "row", justifyContent: "space-between", gap: 5 },
  day: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 9,
    borderRadius: 10,
    backgroundColor: "#edf0ed",
  },
  dayActive: { backgroundColor: "#176b47" },
  dayText: { fontWeight: "700", color: "#68756d" },
  listRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 9,
    borderTopWidth: 1,
    borderTopColor: "#edf0ed",
  },
  todayButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "#c8d8cc",
    borderRadius: 10,
    backgroundColor: "#f4f8f5",
  },
  calendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 4,
  },
  calendarArrow: { paddingHorizontal: 14, fontSize: 30, color: "#176b47" },
  calendarTitle: { fontSize: 20, fontWeight: "800", color: "#20362a" },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderColor: "#dfe5e0",
  },
  weekHeader: {
    width: "14.2857%",
    alignItems: "center",
    paddingVertical: 9,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#dfe5e0",
    backgroundColor: "#f2f5f2",
  },
  weekHeaderText: { fontSize: 12, fontWeight: "700", color: "#59665e" },
  sunday: { color: "#b54a43" },
  saturday: { color: "#426ba8" },
  calendarCell: {
    width: "14.2857%",
    minHeight: 96,
    padding: 7,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#dfe5e0",
    backgroundColor: "#fff",
  },
  calendarToday: { backgroundColor: "#eef8f1" },
  calendarDay: {
    marginBottom: 6,
    fontSize: 12,
    fontWeight: "700",
    color: "#3b4840",
  },
  calendarEvent: {
    marginBottom: 3,
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 4,
    backgroundColor: "#e7f2ea",
    fontSize: 10,
    color: "#245f40",
  },
  more: { fontSize: 10, color: "#7b867f" },
});
