import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  cardTitle: { fontSize: 17, fontWeight: "700", color: "#213128" },
  muted: { marginTop: 3, color: "#748078" },
  todayButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "#c8d8cc",
    borderRadius: 10,
    backgroundColor: "#f4f8f5",
  },
  secondaryText: { fontWeight: "700", color: "#176b47" },
  calendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 4,
  },
  calendarArrow: { paddingHorizontal: 14, fontSize: 30, color: "#176b47" },
  calendarTitle: { fontSize: 20, fontWeight: "800", color: "#20362a" },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderColor: "#dfe5e0",
  },
  weekHeader: {
    width: "14.2857%",
    alignItems: "center",
    paddingVertical: 9,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#dfe5e0",
    backgroundColor: "#f2f5f2",
  },
  weekHeaderText: { fontSize: 12, fontWeight: "700", color: "#59665e" },
  sunday: { color: "#b54a43" },
  saturday: { color: "#426ba8" },
  calendarCell: {
    width: "14.2857%",
    minHeight: 96,
    padding: 7,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#dfe5e0",
    backgroundColor: "#fff",
  },
  calendarToday: { backgroundColor: "#eef8f1" },
  calendarDay: {
    marginBottom: 6,
    fontSize: 12,
    fontWeight: "700",
    color: "#3b4840",
  },
  calendarEvent: {
    marginBottom: 3,
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 4,
    backgroundColor: "#e7f2ea",
    fontSize: 10,
    color: "#245f40",
  },
  more: { fontSize: 10, color: "#7b867f" },
  listRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 9,
    borderTopWidth: 1,
    borderTopColor: "#edf0ed",
  },
  todoTitle: { fontSize: 15, fontWeight: "600", color: "#26372d" },
  done: { color: "#9aa49e", textDecorationLine: "line-through" },
  chip: {
    overflow: "hidden",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 99,
    backgroundColor: "#eaf4ed",
    fontSize: 11,
    color: "#256543",
  },
});
