import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  page: {
    width: "100%",
    maxWidth: 1180,
    alignSelf: "center",
    gap: 14,
    paddingHorizontal: 28,
    paddingTop: 22,
    paddingBottom: 100,
  },
  sectionHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  heading: { fontSize: 30, fontWeight: "800", color: "#17251e" },
  muted: { marginTop: 3, color: "#748078" },
  ghostButton: { padding: 9 },
  ghostText: { fontWeight: "700", color: "#176b47" },
  segment: { flexDirection: "row", gap: 4, padding: 4, borderRadius: 14, backgroundColor: "#e7ece8" },
  segmentItem: { flex: 1, alignItems: "center", paddingVertical: 10, borderRadius: 10 },
  segmentActive: { backgroundColor: "#fff" },
  segmentText: { fontWeight: "600", color: "#738078" },
  segmentTextActive: { color: "#176b47" },
  input: {
    minHeight: 46,
    paddingHorizontal: 13,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#d9e1da",
    borderRadius: 12,
    backgroundColor: "#fbfcfb",
    color: "#17251e",
  },
  row: { flexDirection: "row", alignItems: "center", gap: 8 },
  flex: { flex: 1 },
  primaryButton: {
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    borderRadius: 12,
    backgroundColor: "#176b47",
  },
  disabled: { opacity: 0.4 },
  primaryText: { fontWeight: "700", color: "#fff" },
  empty: { paddingVertical: 45, textAlign: "center", color: "#8a958e" },
});
