import { StyleSheet } from "react-native";

const border = "#E5E7EB";

export const weeklyStyles = StyleSheet.create({
  screen: { flex: 1, minHeight: 0, backgroundColor: "#FFFFFF" },
  toolbar: {
    height: 56,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: border,
  },
  toolbarLeft: { flexDirection: "row", alignItems: "center", gap: 12 },
  arrowButton: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: border,
    borderRadius: 4,
  },
  arrow: { marginTop: -3, fontSize: 25, lineHeight: 27, color: "#111827" },
  range: { fontSize: 18, fontWeight: "600", color: "#111827", fontVariant: ["tabular-nums"] },
  todayButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 4,
    backgroundColor: "#F9FAFB",
  },
  todayButtonText: { fontSize: 11, fontWeight: "700", color: "#4B5563" },
  addButton: {
    width: 110,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 4,
    backgroundColor: "#111111",
  },
  addButtonText: { fontSize: 12, fontWeight: "700", letterSpacing: 0.6, color: "#FFFFFF" },
  workspace: { flex: 1, minHeight: 0, flexDirection: "row" },
  summary: { width: 280, borderRightWidth: 1, borderRightColor: border, backgroundColor: "#F4F4F4" },
  summaryTitleBlock: {
    height: 96,
    justifyContent: "center",
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: border,
  },
  summaryEyebrow: { fontSize: 12, lineHeight: 16, fontWeight: "700", letterSpacing: 1.2, color: "#6B7280" },
  summaryCaption: { marginTop: 3, fontSize: 11, color: "#9CA3AF" },
  selectedDateBlock: {
    height: 72,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: border,
  },
  selectedDateText: {
    marginTop: 3,
    fontSize: 17,
    lineHeight: 20,
    fontWeight: "800",
    letterSpacing: 0.7,
    color: "#111827",
  },
  todayChip: {
    overflow: "hidden",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 3,
    backgroundColor: "#111827",
    fontSize: 10,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  summaryContent: { gap: 8, padding: 16, paddingBottom: 48 },
  summaryHeading: {
    marginTop: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  summarySectionLabel: {
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "700",
    letterSpacing: 0.5,
    color: "#9CA3AF",
  },
  summaryMeta: { fontSize: 11, fontWeight: "700", color: "#6B7280" },
  focusCard: {
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: border,
    borderRadius: 4,
    backgroundColor: "#FFFFFF",
  },
  focusValue: { fontSize: 20, fontWeight: "800", color: "#1F2937" },
  summaryItem: {
    height: 46,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: border,
    borderRadius: 4,
    backgroundColor: "#FFFFFF",
  },
  checkIcon: { fontSize: 12, color: "#111827" },
  summaryItemText: { flex: 1, fontSize: 13, fontWeight: "600", color: "#1F2937" },
  emptyText: { paddingVertical: 8, fontSize: 11, color: "#9CA3AF" },
  memoInputRow: {
    height: 46,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: border,
    borderRadius: 4,
    backgroundColor: "#FFFFFF",
  },
  memoInput: { flex: 1, padding: 0, fontSize: 12, color: "#111827", outlineStyle: "none" } as never,
  memoAdd: { padding: 6, fontSize: 16, fontWeight: "700", color: "#6B7280" },
  memoCard: { padding: 13, borderWidth: 1, borderColor: border, borderRadius: 4, backgroundColor: "#FFFFFF" },
  memoCardTop: { flexDirection: "row", alignItems: "flex-start", gap: 8 },
  memoText: { flex: 1, fontSize: 12, lineHeight: 18, fontWeight: "600", color: "#4B5563" },
  memoDelete: { fontSize: 17, lineHeight: 17, color: "#9CA3AF" },
  memoTime: { marginTop: 7, fontSize: 10, color: "#9CA3AF" },
  calendarArea: { flex: 1, minWidth: 0, minHeight: 0 },
  calendarHeaderRow: {
    height: 168,
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: border,
    backgroundColor: "#FFFFFF",
  },
  axisHeader: {
    width: 64,
    justifyContent: "space-between",
    padding: 8,
    borderRightWidth: 1,
    borderRightColor: border,
  },
  timezone: { fontSize: 10, fontWeight: "700", letterSpacing: 0.4, color: "#9CA3AF" },
  allDayLabel: { fontSize: 9, fontWeight: "700", color: "#6B7280" },
  headerViewport: { flex: 1 },
  dayHeaders: { height: 96, flexDirection: "row", borderBottomWidth: 1, borderBottomColor: border },
  dayHeader: {
    height: 96,
    justifyContent: "space-between",
    padding: 12,
    borderRightWidth: 1,
    borderRightColor: border,
    backgroundColor: "#FFFFFF",
  },
  dayHeaderSelected: { backgroundColor: "#000000" },
  dayHeaderTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  weekday: { fontSize: 10, fontWeight: "700", letterSpacing: 0.5, color: "#6B7280" },
  inverseText: { color: "#FFFFFF" },
  dateBadge: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "#F3F4F6",
  },
  todayBadge: { borderWidth: 1, borderColor: "#111827" },
  selectedBadge: { borderColor: "rgba(255,255,255,0.55)", backgroundColor: "transparent" },
  badgeText: { fontSize: 11, fontWeight: "700", color: "#6B7280" },
  largeDate: { fontSize: 36, lineHeight: 38, fontWeight: "800", color: "#111827" },
  allDayRow: { height: 72, flexDirection: "row", backgroundColor: "#FAFAFA" },
  allDayColumn: {
    height: 72,
    gap: 3,
    paddingHorizontal: 5,
    paddingTop: 7,
    borderRightWidth: 1,
    borderRightColor: border,
  },
  allDayEvent: {
    height: 24,
    justifyContent: "center",
    paddingHorizontal: 7,
    borderWidth: 1,
    borderColor: "#BFDBFE",
    borderRadius: 2,
    backgroundColor: "#DBEAFE",
  },
  allDayEventText: { fontSize: 10, fontWeight: "700", color: "#1E40AF" },
  completedEvent: { opacity: 0.62, borderColor: "#D1D5DB", backgroundColor: "#F3F4F6" },
  completedText: { color: "#9CA3AF", textDecorationLine: "line-through" },
  moreText: { paddingLeft: 4, fontSize: 9, fontWeight: "700", color: "#6B7280" },
  verticalViewport: { flex: 1 },
  timelineRow: { height: 1380, flexDirection: "row" },
  timeAxis: {
    width: 64,
    height: 1380,
    position: "relative",
    borderRightWidth: 1,
    borderRightColor: border,
    backgroundColor: "#FFFFFF",
  },
  hourLabel: {
    position: "absolute",
    right: 8,
    fontSize: 10,
    fontWeight: "500",
    color: "#9CA3AF",
    fontVariant: ["tabular-nums"],
  },
  gridViewport: { flex: 1, height: 1380 },
  grid: { height: 1380, position: "relative", overflow: "hidden", backgroundColor: "#FFFFFF" },
  hourLine: { position: "absolute", left: 0, right: 0, height: 1, backgroundColor: "#E5E7EB" },
  dayColumn: { position: "absolute", top: 0, bottom: 0, borderRightWidth: 1, borderRightColor: border },
  selectedColumn: { backgroundColor: "rgba(249,250,251,0.72)" },
  sessionCard: {
    position: "absolute",
    zIndex: 2,
    minHeight: 24,
    justifyContent: "space-between",
    paddingHorizontal: 7,
    paddingVertical: 5,
    borderWidth: 1,
    borderLeftWidth: 3,
    borderColor: "#BFDBFE",
    borderLeftColor: "#1D4ED8",
    borderRadius: 2,
    backgroundColor: "#EFF6FF",
  },
  sessionTitle: { fontSize: 11, lineHeight: 14, fontWeight: "700", color: "#1E40AF" },
  sessionTime: {
    fontSize: 9,
    lineHeight: 12,
    fontWeight: "600",
    color: "#1E3A8A",
    fontVariant: ["tabular-nums"],
  },
  nowLine: { position: "absolute", zIndex: 4, height: 2, backgroundColor: "#000000" },
  nowDot: {
    position: "absolute",
    left: -5,
    top: -4,
    width: 10,
    height: 10,
    borderWidth: 2,
    borderColor: "#FFFFFF",
    borderRadius: 5,
    backgroundColor: "#000000",
  },
  modalBackdrop: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    backgroundColor: "rgba(0,0,0,0.38)",
  },
  createModal: { width: "100%", maxWidth: 520, padding: 24, borderRadius: 6, backgroundColor: "#FFFFFF" },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  modalTitle: { fontSize: 18, fontWeight: "800", color: "#111827" },
  closeText: { padding: 4, fontSize: 26, lineHeight: 26, color: "#6B7280" },
  fieldLabel: { marginBottom: 6, fontSize: 10, fontWeight: "800", letterSpacing: 0.7, color: "#6B7280" },
  fieldInput: {
    minHeight: 42,
    marginBottom: 16,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 4,
    fontSize: 13,
    color: "#111827",
  },
  noteInput: { minHeight: 82, textAlignVertical: "top" },
  readonlyField: {
    height: 42,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: border,
    borderRadius: 4,
    backgroundColor: "#F9FAFB",
  },
  readonlyText: { fontSize: 13, color: "#111827", fontVariant: ["tabular-nums"] },
  allDayPill: {
    overflow: "hidden",
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 3,
    backgroundColor: "#DBEAFE",
    fontSize: 9,
    fontWeight: "800",
    color: "#1E40AF",
  },
  modalActions: { flexDirection: "row", justifyContent: "flex-end", gap: 10, paddingTop: 6 },
  cancelButton: {
    height: 38,
    justifyContent: "center",
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 4,
  },
  cancelText: { fontSize: 12, fontWeight: "700", color: "#4B5563" },
  saveButton: {
    height: 38,
    justifyContent: "center",
    paddingHorizontal: 20,
    borderRadius: 4,
    backgroundColor: "#111827",
  },
  saveText: { fontSize: 12, fontWeight: "700", color: "#FFFFFF" },
  disabled: { opacity: 0.4 },
  drawerOverlay: { flex: 1, flexDirection: "row", justifyContent: "flex-end" },
  drawerBackdrop: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: "rgba(0,0,0,0.22)",
  },
  drawer: {
    width: 400,
    maxWidth: "90%",
    borderLeftWidth: 1,
    borderLeftColor: border,
    backgroundColor: "#FFFFFF",
  },
  drawerHeader: {
    height: 61,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 22,
    borderBottomWidth: 1,
    borderBottomColor: border,
    backgroundColor: "#FDFDFD",
  },
  drawerTag: {
    overflow: "hidden",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 3,
    backgroundColor: "#111827",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.6,
    color: "#FFFFFF",
  },
  drawerContent: { flexGrow: 1, gap: 12, padding: 24 },
  drawerTitle: { fontSize: 22, lineHeight: 28, fontWeight: "800", color: "#111827" },
  drawerMeta: { fontSize: 12, lineHeight: 18, color: "#6B7280" },
  noteBox: {
    marginTop: 8,
    padding: 14,
    borderWidth: 1,
    borderColor: border,
    borderRadius: 4,
    backgroundColor: "#F9FAFB",
  },
  noteBoxText: { fontSize: 13, lineHeight: 20, color: "#4B5563" },
  drawerFooter: {
    height: 68,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 10,
    paddingHorizontal: 22,
    borderTopWidth: 1,
    borderTopColor: border,
  },
  deleteButton: {
    height: 38,
    justifyContent: "center",
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: "#FCA5A5",
    borderRadius: 4,
  },
  deleteText: { fontSize: 12, fontWeight: "700", color: "#B91C1C" },
  completeButton: {
    height: 38,
    justifyContent: "center",
    paddingHorizontal: 18,
    borderRadius: 4,
    backgroundColor: "#111827",
  },
});
