import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#f5f7f4" },
  mobileShell: { flex: 1 },
  desktopShell: { flex: 1, flexDirection: "row" },
  mainColumn: { flex: 1, minWidth: 0 },
  topbar: {
    minHeight: 68,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#dfe5df",
    backgroundColor: "#fff",
  },
  desktopTopbar: { minHeight: 82, paddingHorizontal: 34, backgroundColor: "#f8faf7" },
  brand: { fontSize: 24, fontWeight: "800", color: "#173829" },
  email: { marginTop: 3, fontSize: 12, color: "#7c8780" },
  topActions: { flexDirection: "row", gap: 16 },
  topActionButton: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderWidth: 1,
    borderColor: "#d6e1d9",
    borderRadius: 10,
    backgroundColor: "#fff",
  },
  refresh: { fontSize: 12, fontWeight: "600", color: "#176b47" },
  logout: { fontSize: 12, fontWeight: "600", color: "#7a5b56" },
  errorBar: { alignItems: "center", padding: 8, backgroundColor: "#fff0ed" },
  errorText: { fontSize: 12, color: "#a23c32" },
  content: { flex: 1 },
  desktopContent: { backgroundColor: "#f8faf7" },
  loader: { flex: 1 },
  desktopNav: {
    width: 236,
    padding: 18,
    gap: 6,
    borderRightWidth: 1,
    borderRightColor: "#dce4dd",
    backgroundColor: "#fff",
  },
  desktopNavHeader: { paddingHorizontal: 10, paddingTop: 8, paddingBottom: 24 },
  desktopLogo: { fontSize: 28, fontWeight: "900", color: "#173829" },
  desktopCaption: { marginTop: 3, fontSize: 11, color: "#89938d" },
  desktopNavItem: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    paddingHorizontal: 14,
    borderRadius: 12,
  },
  desktopNavSelected: { backgroundColor: "#eaf4ed" },
  desktopNavLabel: { fontSize: 14, fontWeight: "600", color: "#68756d" },
  desktopAccount: { marginTop: "auto", gap: 8, padding: 12, borderTopWidth: 1, borderTopColor: "#e6ebe7" },
  desktopEmail: { fontSize: 11, color: "#77837b" },
  dashboard: { flex: 1, flexDirection: "row", gap: 12, padding: 12, overflow: "hidden" },
  dashboardPrimary: { flex: 1.65, minWidth: 0, gap: 12 },
  dashboardPanel: {
    minHeight: 0,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#dce3dd",
    borderRadius: 16,
    backgroundColor: "#fff",
  },
  todoPanel: { flex: 1.2 },
  memoPanel: { flex: 1 },
  timePanel: { flex: 1, minWidth: 390 },
  nav: {
    flexDirection: "row",
    paddingTop: 7,
    paddingBottom: Platform.OS === "ios" ? 4 : 8,
    borderTopWidth: 1,
    borderTopColor: "#dce3dd",
    backgroundColor: "#fff",
  },
  navItem: { flex: 1, alignItems: "center", gap: 2 },
  navIcon: { fontSize: 20, color: "#89938d" },
  navLabel: { fontSize: 11, fontWeight: "600", color: "#89938d" },
  navActive: { color: "#176b47" },
});
