import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  cardTitle: { fontSize: 17, fontWeight: "700", color: "#213128" },
  input: {
    minHeight: 46,
    paddingHorizontal: 13,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#d9e1da",
    borderRadius: 12,
    backgroundColor: "#fbfcfb",
    color: "#17251e",
  },
  weekdays: { flexDirection: "row", justifyContent: "space-between", gap: 5 },
  day: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 9,
    borderRadius: 10,
    backgroundColor: "#edf0ed",
  },
  dayActive: { backgroundColor: "#176b47" },
  dayText: { fontWeight: "700", color: "#68756d" },
  primaryText: { fontWeight: "700", color: "#fff" },
  secondaryButton: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 15,
    borderWidth: 1,
    borderColor: "#bad0c1",
    borderRadius: 12,
    backgroundColor: "#eef6f1",
  },
  secondaryText: { fontWeight: "700", color: "#176b47" },
  listRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 9,
    borderTopWidth: 1,
    borderTopColor: "#edf0ed",
  },
  flex: { flex: 1 },
  todoTitle: { fontSize: 15, fontWeight: "600", color: "#26372d" },
  done: { color: "#9aa49e", textDecorationLine: "line-through" },
  meta: { fontSize: 11, color: "#7b867f" },
  danger: { color: "#a43d35" },
});
