import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  sectionHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  cardTitle: { fontSize: 17, fontWeight: "700", color: "#213128" },
  muted: { marginTop: 3, color: "#748078" },
  row: { flexDirection: "row", alignItems: "center", gap: 8 },
  flex: { flex: 1 },
  input: {
    minHeight: 46,
    paddingHorizontal: 13,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#d9e1da",
    borderRadius: 12,
    backgroundColor: "#fbfcfb",
    color: "#17251e",
  },
  primaryText: { fontWeight: "700", color: "#fff" },
  secondaryText: { fontWeight: "700", color: "#176b47" },
  plannerArrow: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#d7dfd9",
    borderRadius: 9,
    backgroundColor: "#fff",
  },
  todayButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "#c8d8cc",
    borderRadius: 10,
    backgroundColor: "#f4f8f5",
  },
  planner: { minWidth: 820, marginTop: 12, borderTopWidth: 1, borderLeftWidth: 1, borderColor: "#aeb8b1" },
  plannerHeader: { flexDirection: "row" },
  timeHeader: {
    width: 52,
    height: 52,
    alignItems: "center",
    justifyContent: "center",
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#aeb8b1",
    backgroundColor: "#f3f5f3",
  },
  meta: { fontSize: 11, color: "#7b867f" },
  plannerDayHeader: {
    width: 108,
    height: 52,
    alignItems: "center",
    justifyContent: "center",
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#aeb8b1",
    backgroundColor: "#f8faf8",
  },
  plannerDayName: { fontWeight: "800", color: "#38463d" },
  sunday: { color: "#b54a43" },
  saturday: { color: "#426ba8" },
  plannerRow: { flexDirection: "row" },
  timeCell: {
    width: 52,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#aeb8b1",
    backgroundColor: "#f8faf8",
  },
  timeLabel: { fontSize: 11, color: "#5f6a63" },
  plannerCell: {
    width: 108,
    height: 46,
    padding: 2,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#aeb8b1",
    backgroundColor: "#fff",
  },
  studyBlock: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 5,
    borderRadius: 3,
    backgroundColor: "#dcefe2",
  },
  studyText: { fontSize: 9, fontWeight: "600", color: "#245d3d" },
  miniButton: {
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "#176b47",
  },
  listRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 9,
    borderTopWidth: 1,
    borderTopColor: "#edf0ed",
  },
  todoTitle: { fontSize: 15, fontWeight: "600", color: "#26372d" },
  danger: { color: "#a43d35" },
});
