import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  page: {
    width: "100%",
    maxWidth: 1180,
    alignSelf: "center",
    gap: 14,
    paddingHorizontal: 28,
    paddingTop: 22,
    paddingBottom: 100,
  },
  heading: { fontSize: 30, fontWeight: "800", color: "#17251e" },
  muted: { marginTop: 3, color: "#748078" },
  timeTopGrid: { flexDirection: "row", flexWrap: "wrap", alignItems: "stretch", gap: 14 },
  timePanel: { flexGrow: 1, flexBasis: 390 },
  segment: { flexDirection: "row", gap: 4, padding: 4, borderRadius: 14, backgroundColor: "#e7ece8" },
  segmentItem: { flex: 1, alignItems: "center", paddingVertical: 10, borderRadius: 10 },
  segmentActive: { backgroundColor: "#fff" },
  segmentText: { fontWeight: "600", color: "#738078" },
  segmentTextActive: { color: "#176b47" },
  timer: {
    marginVertical: 24,
    textAlign: "center",
    fontSize: 66,
    fontVariant: ["tabular-nums"],
    fontWeight: "800",
    color: "#153c2a",
  },
  input: {
    minHeight: 46,
    paddingHorizontal: 13,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#d9e1da",
    borderRadius: 12,
    backgroundColor: "#fbfcfb",
    color: "#17251e",
  },
  focusDots: { flexDirection: "row", justifyContent: "center", gap: 7 },
  focusDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: "#d4dcd6" },
  focusDotActive: { backgroundColor: "#1c7a50" },
  timerHint: { textAlign: "center", fontSize: 11, color: "#758078" },
  row: { flexDirection: "row", alignItems: "center", gap: 8 },
  flex: { flex: 1 },
  primaryButton: {
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    borderRadius: 12,
    backgroundColor: "#176b47",
  },
  primaryText: { fontWeight: "700", color: "#fff" },
  secondaryButton: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 15,
    borderWidth: 1,
    borderColor: "#bad0c1",
    borderRadius: 12,
    backgroundColor: "#eef6f1",
  },
  secondaryText: { fontWeight: "700", color: "#176b47" },
});
